FROM node:20-slim

WORKDIR /app

COPY sim-services/gateway/package.json ./
COPY sim-services/gateway/gateway.js ./
COPY sim-services/gateway/sim.proto ./

RUN npm install

CMD ["node", "gateway.js"]

